### ISSUE TITLE
Internal Server Error when self promoting to teacher

### ISSUE THREAD

**Issue by Destidom** [autograde/aguis#102]
```
1 errors prohibited Group from being saved:
Internal Server Error
```

_Originally posted by @meling in https://github.com/autograde/aguis/issues/101#issuecomment-434705899_

**Comment by 0xf8f8ff** [comment]
Teacher enrollment status is related to an existing course, which, in turn, is related to a GitHub organization. Therefore, enrolled users can only be promoted to teachers by other course teachers, because the one promoting must already have organization ownership. The ownership  will be granted on promotion.
