### ISSUE TITLE
Some feature Wishlist and bugs if its not already fixed..

### ISSUE THREAD

**Issue by vinaysetty** [autograde/aguis#177]
just a few more wishlist that comes to my mind.. 

1. it would be nice to also see the build time, currently only build date is shown, this is to make it easy to identify if the build was successful, right now the only way to see that is to keep observing build id
2. It would be nice to be able to unapprove an assignment which was accidentally approved, there was a bug when some students were automatically approved with 0% score even though the assignment was marked as manual approval
3. Seems like the docker problem still exists, some containers with exit status stay around and it also gives an error when trying to rebuild
For example,
docker ps -a 
gives
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                     PORTS               NAMES
4ab4f44e23d8        python:3.6.1        "/bin/sh -c 'echo ..."   5 minutes ago       Exited (0) 3 minutes ago                       khoaln
during that when I try to rebuild it gives the following error "Docker execution failed{error 25 0  Error response from daemon: Conflict. The container name "/khoaln" is already in use by container"
4. Would be nice when a test case is changed all the assignment submissions are rebuilt..

**Comment by meling** [comment]
@vinaysetty Can you check whether or not items 1 and 2 are still a problem. I believe they have been resolved.

As for item 3, we hope that this will be resolved when we move to a new VM with more up-to-date Linux kernel (and by extension Docker). Hence, unless there is an immediate problem, we won't try to fix that.

Item 4: I only now realize what this said, and it's a good idea.

We can probably be more targeted than "all submissions", since we can check which assignment was changed in the tests repo, and rerun only the last submissions for a specific assignment. Hence, this sounds like a worthwhile thing to implement.

I believe it should be relatively easy to implement; do you want to give it a go @vinaysetty ? 
If so, maybe you want to start a separate issue to discuss design etc.

You can take a look at [UpdateTestsFromRepo](https://github.com/autograde/aguis/blob/master/assignments/assignments.go#L17) and elsewhere in the `assignments` package. The update is triggered from the [web/hooks](https://github.com/autograde/aguis/blob/master/web/hooks/github.go#L76) package, which contains a few functions that can probably be reused.

**Comment by vinaysetty** [comment]
@meling I checked 1 and 2 are fixed. So 3 won't be a relevant bug anymore in the new system right? and 4 I will create a new issue. Lets continue the discussion there.
