### ISSUE TITLE
Error when students create folders 

### ISSUE THREAD

**Issue by vinaysetty** [autograde/aguis#182]
If students create a new folder (top level) under username-labs repository, autograder seems to consider it as a new assignment and tries to look for tests and fails and this may cause errors like nil pointer exception etc. One option would be for autograder to ignore it. We can also instruct students to not do that of course.

**Comment by meling** [comment]
I belive this has been fixed. Autograder no longer crashes due to folder/content at the top level, but changes that are not related to a specific lab will not trigger CI execution. Hence, it is not recommended to keep content at the top level folder of the repo, since AG has no way to infer which lab was modified, and which tests should be executed. Closing this as I'm not sure what more we can do. Feel free to reopen if you have other ideas.
