### ISSUE TITLE
Frontend does not let me in on first attempt

### ISSUE THREAD

**Issue by meling** [autograde/aguis#48]
When I try to login with github it redirects me back to the front page again. Next time I try, it redirects correctly to github to ask for pw. Not sure if this is a frontend or backend redirection issue?

**Comment by s111** [comment]
It's the backend doing this and it's intentional. The reason this happens is that you have a cookie that says that you are logged in, but it's no longer valid, so the backend delete the cookie (logs you out). We could redirect directly back to github, but I'm afraid we could end up with a "redirect loop" in some cases, and it would be better to just show a `you've been logged out` or `you need to reauthenticate, click here` message.

**Comment by meling** [comment]
Yeah, I think that would be friendly.

**Comment by meling** [comment]
In the old autograder, I can sign in days or weeks later without my cookie being outdated, or so it seems at least. The same seems to work for other services such as travis-ci and buddy that allow sign in with github.

**Comment by Destidom** [comment]
Reopen if this problem reappears.
